### PR TITLE
Update to redmine 1.4

### PR DESCRIPTION
**Pull request by sawicki-maciej**
Hi I updated your Patch to support Redmine 1.4. Could check it and if it O.K. merge it with your branch?

### CODE REVIEW

**Comment by arthurblake** [comment]
Is this stable and working well?

**Comment by arthurblake** [comment]
I tried installing your 1.4 patch, and now redmine will not start - I get the following error message from Phusion Passenger:

Error message:
Could not find gem 'mocha (>= 0) ruby' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

I can send you a screen shot with the back trace if you like.  Let me know.

**Comment by arthurblake** [comment]
More information:
I tried applying the patch against both 1.0.5 turnkey and 1.3.2 turnkey (upgraded with  ripuk / TKLPatch-Redmine) In both cases, I get the same result as indicated above.

Also, when applying the 1.4.0 patch, I get this message at the end:

Some gems may need to be installed or updated.
Please run `bundle install --without development test`.

Thank goodness for VM snapshots!

**Comment by davestephens** [comment]
Hmmm....weird. Seems a little odd you got it with my patch as it worked fine on my instance. 

I'll do some testing this week...

**Comment by did-vmonroig** [comment]
Sorry, but after a server restart, same error that for arthurblake is shown:

Could not find gem 'mocha (>= 0) ruby' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

This is the command sequence I used in order to make it work again:

gem install mocha
gem install pg
gem install coderay
gem install fastercsv
gem install tzinfo
gem install net-ldap
gem install ruby-openid -v "~> 2.1.4"
gem install rmagick
gem install sqlite3
gem install mysql2 -v "~> 0.2.7"
gem install rdoc
gem install shoulda -v "~> 2.10.3"
gem install edavis10-object_daddy
cd /var/www/railsapp/
bundle install
rake db:migrate RAILS_ENV=production

**Pull request closed without merging**
